#!/bin/bash

echo "Video Converter - Input file is a mjpg"
echo "Provide input filename"

read inputfile

echo "Choose the output filename with format (Example: output.mkv, 
output.mpeg, output.avi, ...)"

read outputfile

avconv -i "$inputfile" -vcodec copy "$outputfile"

echo "Finished"
